---
- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Shutdown existing primary server
  when: "'primary_servers' in group_names"
  service: name=postgresql state=stopped

- name: Write the trigger file
  when: "'standby_servers' in group_names"
  file: path=/var/lib/postgresql/9.6/FAILOVER owner=postgres group=postgres mode=0700 state=touch

- name: Wait for the failover to complete
  when: "'standby_servers' in group_names"
  wait_for: path=/var/lib/postgresql/9.6/FAILOVER state=absent

- name: Turn on archiving at the promoted server
  when: "'standby_servers' in group_names"
  file: path=/var/lib/postgresql/9.6/NOARCHIVE state=absent
